# Generated by Django 4.1.3 on 2022-11-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_suscripciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripciones',
            name='fecha',
        ),
    ]
