# Generated by Django 4.1.3 on 2022-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_suscripciones_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripciones',
            name='duracion',
        ),
    ]
