# Generated by Django 4.1.3 on 2022-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_suscripciones_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripciones',
            name='duracion',
            field=models.FloatField(default=1.0),
        ),
    ]
