# Generated by Django 4.1.3 on 2022-11-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_order_created_at_order_paid_order_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
