# Generated by Django 4.1.3 on 2022-12-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_rename_orden_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(default='anything', upload_to='productos/imagenes'),
        ),
    ]
