# Generated by Django 4.1.3 on 2022-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_musica_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='imagen',
            field=models.ImageField(default='anything', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
