# Generated by Django 4.1.3 on 2022-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_peliculas_imagen_alter_musica_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escaparates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('canciones', models.ManyToManyField(to='productos.musica')),
                ('peliculas', models.ManyToManyField(to='productos.peliculas')),
                ('suscripciones', models.ManyToManyField(to='productos.suscripciones')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
