# Generated by Django 4.1.3 on 2022-12-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_escaparates_canciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaparates',
            name='canciones',
        ),
        migrations.RemoveField(
            model_name='escaparates',
            name='suscripciones',
        ),
    ]
