# Generated by Django 4.1.3 on 2022-12-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_remove_escaparates_canciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaparates',
            name='canciones',
            field=models.ManyToManyField(to='productos.musica'),
        ),
        migrations.AddField(
            model_name='escaparates',
            name='suscripciones',
            field=models.ManyToManyField(to='productos.suscripciones'),
        ),
    ]
