# Generated by Django 4.1.3 on 2022-12-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_escaparates_canciones_escaparates_suscripciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escaparates',
            options={},
        ),
    ]
