# Generated by Django 4.1.3 on 2022-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_escaparates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaparates',
            name='fecha_modificación',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
