# Generated by Django 4.1.3 on 2022-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_remove_escaparates_fecha_modificación_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaparates',
            name='canciones',
            field=models.ManyToManyField(blank=True, to='productos.musica'),
        ),
        migrations.AlterField(
            model_name='escaparates',
            name='peliculas',
            field=models.ManyToManyField(blank=True, to='productos.peliculas'),
        ),
        migrations.AlterField(
            model_name='escaparates',
            name='suscripciones',
            field=models.ManyToManyField(blank=True, to='productos.suscripciones'),
        ),
    ]
