# Generated by Django 4.1.3 on 2022-12-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_pedido_end_date_pedido_notified_pedido_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='duration',
            field=models.DurationField(),
        ),
    ]
