# Generated by Django 4.1.3 on 2022-12-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_peliculas_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='redemption_date',
            field=models.DateTimeField(null=True),
        ),
    ]
