# Generated by Django 4.1.3 on 2022-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_alter_pedido_redemption_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='purchase_date',
        ),
    ]
