# Generated by Django 4.1.3 on 2022-12-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_remove_pedido_redeemed_remove_pedido_redemption_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='end_date',
        ),
        migrations.AddField(
            model_name='elementopedido',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
