# Generated by Django 4.1.3 on 2022-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_remove_pedido_end_date_elementopedido_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripciones',
            name='canciones',
            field=models.ManyToManyField(blank=True, to='productos.musica'),
        ),
        migrations.AddField(
            model_name='suscripciones',
            name='peliculas',
            field=models.ManyToManyField(blank=True, to='productos.peliculas'),
        ),
    ]
