# Generated by Django 4.1.3 on 2022-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_suscripciones_canciones_suscripciones_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='apellidos',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
